# DSC 550 [TITLE PLACEHOLDER]

## LIBRARIES

In [9]:
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import scienceplots

## Figure Configuration

In [13]:
# Figure style
plt.style.use(['science', 'no-latex'])

# Color palette
sns.set_palette("colorblind")

# Global parameters for figures
mpl.rcParams.update({
    'figure.dpi': 600,
    'font.family': 'serif',
    'font.size': 12,
    'axes.titlesize': 14,
    'axes.labelsize': 12,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'axes.spines.top': False,
    'axes.spines.right': False
})

## Chapter 1: Birth Rates

### Global Fertility Rates

In [ ]:
global_fertility_rate = pd.read_csv('data/Birth Rate & Natality Trends/global_birth_rate_1960_2024.csv')
global_fertility_rate.head()

,Country Name,Country Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,4.57,4.42,4.26,4.11,3.94,3.80,3.62,3.45,...,1.90,1.85,1.79,1.73,1.70,1.66,1.63,1.62,1.60,1.61
1,Africa Eastern and Southern,AFE,6.65,6.67,6.69,6.71,6.72,6.74,6.77,6.78,...,4.68,4.62,4.57,4.52,4.47,4.41,4.35,4.29,4.22,4.16
2,Afghanistan,AFG,7.28,7.28,7.29,7.30,7.30,7.31,7.32,7.34,...,5.65,5.54,5.43,5.33,5.24,5.15,5.04,4.93,4.84,4.76
3,Africa Western and Central,AFW,6.47,6.48,6.49,6.50,6.52,6.53,6.56,6.58,...,5.35,5.23,5.10,4.96,4.83,4.71,4.64,4.56,4.50,4.42
4,Angola,AGO,6.71,6.79,6.87,6.95,7.04,7.12,7.19,7.27,...,5.77,5.69,5.60,5.52,5.44,5.37,5.30,5.21,5.12,5.05

### U.S. Birth Rates

In [16]:
us_birth_rate = pd.read_csv('data/Birth Rate & Natality Trends/birth_rate_2003_2024.csv')
us_birth_rate.head()

     State  Year  Births Total Population Birth Rate
0  Alabama  2003   59552          4503491      13.22
1  Alabama  2004   59510          4530729      13.13
2  Alabama  2005   60453          4569805      13.23
3  Alabama  2006   63232          4628981      13.66
4  Alabama  2007   64804          4672840      13.87

## Chapter 2: Socioeconomic Analysis

### Force 1: Economic Precarity

#### Poverty rate (1980-2025) - *in thousands*

In [18]:
poverty_rate = pd.read_csv('data/Force 1 - Economic Precarity/poverty_rate_by_state_1980_2024.csv')
poverty_rate.head()

,State,Year,Total population,Number in poverty,Margin of error (±) (29),Percent in poverty,Margin of error (±) (29).1
0,Alabama,2024,"5,042",822,141,16.3,2.8
1,Alaska,2024,720,68,13,9.4,1.8
2,Arizona,2024,"7,567",761,124,10.1,1.7
3,Arkansas,2024,"3,011",398,72,13.2,2.4
4,California,2024,"39,440","4,095",351,10.4,0.9

#### Housing Pressure

##### House price index at county level

In [20]:
hpi_county = pd.read_csv('data/Force 1 - Economic Precarity/house price index/house_price_index_at_county.csv')
hpi_county.head()

  State   County  Year  Annual Change (%)     HPI
0    AL  Autauga  1986                NaN  100.00
1    AL  Autauga  1987              -1.86   98.14
2    AL  Autauga  1988               2.60  100.68
3    AL  Autauga  1989               4.30  105.02
4    AL  Autauga  1990              -0.33  104.67

##### House price index at the state level

In [22]:
hpi_state = pd.read_csv('data/Force 1 - Economic Precarity/house price index/house_price_index_at_state.csv')
hpi_state.head()

,State,Abbreviation,Year,Annual Change (%),HPI,HPI with 1990 base,HPI with 2000 base,Unnamed: 7
0,Alabama,AL,1975,NaN,100.00,48.78,35.36,NaN
1,Alabama,AL,1976,8.21,108.21,52.79,38.26,NaN
2,Alabama,AL,1977,10.35,119.41,58.25,42.23,NaN
3,Alabama,AL,1978,7.90,128.85,62.85,45.56,NaN
4,Alabama,AL,1979,10.88,142.87,69.69,50.52,NaN

##### House price index at the national level

In [23]:
hpi_national = pd.read_csv('data/Force 1 - Economic Precarity/house price index/house_price_index_at_national.csv')
hpi_national.head()

   Year  Annual Change (%)     HPI  HPI with 1990 base  HPI with 2000 base
0  1975                NaN  100.00               32.60               24.35
1  1976               8.13  108.13               35.25               26.33
2  1977              16.10  125.54               40.92               30.57
3  1978              16.12  145.78               47.52               35.50
4  1979              13.92  166.08               54.14               40.44

#### Homeownership

##### Homeownership rate by age cohort (1982-2024)

In [25]:
homeownership_age = pd.read_csv('data/Force 1 - Economic Precarity/homeownership/homeownership_rate_by_age_cohort_1982_2024.csv')
homeownership_age.head()

,Year,U.S. Total,< 25 years,25 - 29,30 - 34,35 - 39,40 - 44,45 - 49,50 - 54,55 - 59,60 - 64,65 - 69,70 - 74,75+
0,1982,64.8,19.3,38.6,57.1,67.6,73.0,76.0,78.8,80.0,80.1,77.9,75.2,71.0
1,1983,64.6,18.8,38.3,55.4,66.5,72.8,75.3,78.8,80.1,79.8,78.7,75.4,71.9
2,1984,64.5,17.9,38.6,54.8,66.1,72.3,74.6,78.4,80.1,79.9,79.3,75.5,71.5
3,1985,63.9,17.2,37.7,54.0,65.4,71.4,74.3,77.5,79.2,79.9,79.5,76.8,69.8
4,1986,63.8,17.2,36.7,53.6,64.8,70.5,74.1,78.1,80.0,79.8,79.4,77.2,70.0

##### Homeownership rate by state (1984-2023)

In [26]:
homeownership_state = pd.read_csv('data/Force 1 - Economic Precarity/homeownership/homeownership_rate_by_state_1984_2023.csv')
homeownership_state.head()

,U.S.,1984,1985,1986,1987,1988,1989,1990,1991,1992,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Countrywide,64.5,63.9,63.8,64.0,63.8,63.9,63.9,64.1,64.1,...,64.5,63.7,63.4,63.9,64.4,64.6,66.6,65.5,65.8,65.9
1,Alabama,73.7,70.4,70.3,67.9,66.5,67.6,68.4,69.9,70.3,...,72.1,70.0,69.7,70.0,70.3,70.7,74.8,73.4,72.1,73.8
2,Alaska,57.6,61.2,61.5,59.7,57.0,58.7,58.4,57.1,55.5,...,64.9,62.3,65.2,65.5,63.7,62.6,64.1,64.0,65.1,64.3
3,Arizona,65.2,64.7,62.5,63.3,66.1,63.9,64.5,66.3,69.3,...,63.5,61.7,61.9,64.4,65.7,65.8,68.7,65.2,68.1,69.7
4,Arkansas,65.9,66.6,67.5,68.1,67.0,66.3,67.8,68.6,70.3,...,65.4,67.1,67.6,65.0,64.7,65.3,68.8,66.1,66.8,65.9

#### Household debt burden and financial constraints

##### Total debt balance and its composition (2003-2025) - *in trillions*

In [33]:
debt_by_composition = pd.read_csv('data/Force 1 - Economic Precarity/debt/total_debt_balance_and_its_composition_2003_2025.csv')
debt_by_composition.head()

,Year,Mortgage,HE Revolving,Auto Loan,Credit Card,Student Loan,Other,Total
0,03:Q1,4.94,0.24,0.64,0.69,0.24,0.48,7.23
1,03:Q2,5.08,0.26,0.62,0.69,0.24,0.49,7.38
2,03:Q3,5.18,0.27,0.68,0.69,0.25,0.48,7.56
3,03:Q4,5.66,0.30,0.70,0.70,0.25,0.45,8.07
4,04:Q1,5.84,0.33,0.72,0.70,0.26,0.45,8.29

##### Total debt balance by age cohort (1999-2025) - *in trillions*

In [34]:
debt_by_age = pd.read_csv('data/Force 1 - Economic Precarity/debt/total_debt_balance_by_age_1999_2025.csv')
debt_by_age.head()

    Year  18-29  30-39  40-49  50-59  60-69   70+
0  99:Q1   0.35   1.22   1.46   0.98   0.38  0.18
1  99:Q2   0.37   1.26   1.49   1.00   0.38  0.18
2  99:Q3   0.42   1.33   1.54   1.02   0.38  0.18
3  99:Q4   0.43   1.33   1.53   1.00   0.37  0.18
4  00:Q1   0.39   1.35   1.64   1.13   0.43  0.21

##### Total debt share by product type and age (2025) - *in trillions*

In [35]:
debt_by_age_productType = pd.read_csv('data/Force 1 - Economic Precarity/debt/total_debt_share_by_product_type_and_age_2025.csv')
debt_by_age_productType.head()

      Debt  Type  18-29  30-39  40-49  50-59  60-69   70+
0     Auto Loans   0.21   0.38   0.40   0.34   0.22  0.12
1    Credit Card   0.09   0.23   0.30   0.28   0.21  0.16
2       Mortgage   0.57   2.88   3.57   2.95   1.95  1.24
3          HELOC   0.00   0.04   0.10   0.12   0.10  0.07
4  Student Loans   0.33   0.51   0.37   0.25   0.12  0.04

##### Total mortgage originations by age (2000-2025) - *in billions*

In [36]:
mortgage_originations = pd.read_csv('data/Force 1 - Economic Precarity/debt/total_mortgage_originations_by_age_2000_2025.csv')
mortgage_originations.head()

  quarter  18-29  30-39  40-49  50-59  60-69   70+
0   00:Q1   30.0   90.6   91.3   59.6   22.7  11.5
1   00:Q2   28.0   76.1   67.2   46.1   12.5   7.4
2   00:Q3   35.6   95.8   83.2   50.2   20.5   9.2
3   00:Q4   36.4   96.2   92.8   48.1   15.7   9.5
4   01:Q1   34.5  103.7  101.8   64.2   21.1  11.5

#### Labor Market Stress

##### Unemployment Rate Among Young Americans

In [ ]:
unemployment_rate = pd.read_csv('data/Force 1 - Economic Precarity/unemployment_rate_among_young_americans.csv')
unemployment_rate.head()

,Date,NBER Recession Indicator,High School,College Unemployment,Smoothed High School,Smoothed College,Raw Gap,Smoothed Gap
0,1/1/76,0,12.426647,5.968664,10.498881,6.162089,6.457983,4.336791
1,2/1/76,0,12.802365,4.980609,10.436311,6.209505,7.821756,4.226806
2,3/1/76,0,12.095907,4.947167,10.410250,6.246098,7.148740,4.164153
3,4/1/76,0,9.946402,4.998806,10.403831,6.271151,4.947595,4.132680
4,5/1/76,0,9.438096,5.624336,10.397664,6.287268,3.813761,4.110396

##### Job Finding & Discouragement Rate

In [38]:
discouragement_rate = pd.read_csv('data/Force 1 - Economic Precarity/job_finding_and_discouragement_rate_2000_2025.csv')
discouragement_rate.head()

,Date,NBER Recession Indicator,Short-Term High School,Short-Term College,Long-Term High School,Long-Term College,Short-Term High School.1,Short-Term College.1,Long-Term High School.1,Long-Term College.1
0,1/1/00,0,33.088963,42.438408,28.484180,39.484088,21.875291,17.015074,21.390061,15.189830
1,2/1/00,0,33.076517,43.041642,28.466562,39.440076,21.982750,16.991066,21.406267,15.219228
2,3/1/00,0,33.094758,43.554063,28.448293,39.395298,21.979497,16.959294,21.422037,15.248274
3,4/1/00,0,33.133503,43.898226,28.429350,39.349737,21.873927,16.978147,21.437400,15.276947
4,5/1/00,0,33.162583,44.031142,28.409715,39.303391,21.705694,17.081706,21.452395,15.305320

#### National Childcare Costs (2023)

In [39]:
childcare_cost = pd.read_csv('data/Force 1 - Economic Precarity/us_childcare_prices_by_child_age_and_care.csv')
childcare_cost.head()

,State name,County name,Infant center-based price: 2018 ($),Infant center-based price: 2023 (estimated) ($),Infant center-based price as share of family income: 2018 (%),Infant home-based price: 2018 ($),Infant home-based price: 2023 (estimated) ($),Infant home-based price as share of family income: 2018 (%),Toddler center-based price: 2018 ($),Toddler center-based price: 2023 (estimated) ($),...,School-age home-based price as share of family income: 2018 (%),Women's labor force participation rate (%),Women's median earnings ($),Median family income ($),Percent of families in poverty (%),Total population,Percent Asian (%),Percent Black (%),Percent Hispanic (of any race) (%),Percent White (%)
0,Alabama,Autauga County,"6,261","7,370",8.5,"5,569","6,555",7.6,"6,261","7,370",...,7.4,66.2,"26,243","73,530",12.0,"55,200",1.0,19.1,2.8,76.9
1,Alabama,Baldwin County,"6,261","7,370",8.7,"5,614","6,608",7.8,"6,261","7,370",...,7.8,70.1,"25,308","71,951",7.3,"208,107",0.8,9.5,4.5,86.3
2,Alabama,Barbour County,"4,482","5,276",10.1,"4,247","4,999",9.6,"4,482","5,276",...,8.4,60.8,"20,396","44,339",21.5,"25,782",0.4,47.6,4.3,47.4
3,Alabama,Bibb County,"5,451","6,416",9.9,"4,530","5,332",8.3,"5,451","6,416",...,8.3,59.5,"22,416","54,840",10.5,"22,527",0.2,22.3,2.4,76.7
4,Alabama,Blount County,"9,260","10,900",15.5,"5,661","6,663",9.5,"9,260","10,900",...,8.3,56.3,"27,579","59,882",10.2,"57,645",0.3,1.5,9.1,95.5

### Force 2: Time Scarcity

#### Labor force participation

##### Labor force participation - *Men (1948-2025)*

In [40]:
lfp_men = pd.read_csv('data/Force 2 - Time Scarcity/labor force participation rate/labor_force_participation_rate_men_20_up.csv')
lfp_men.head()

     Date  Rate
0  1/1/48  87.9
1  2/1/48  88.1
2  3/1/48  87.8
3  4/1/48  88.1
4  5/1/48  88.1

##### Labor force participation - *Women (1948-2025)*

In [41]:
lfp_women = pd.read_csv('data/Force 2 - Time Scarcity/labor force participation rate/labor_force_participation_rate_women_20_up.csv')
lfp_women.head()

     Date  Rate
0  1/1/48  30.1
1  2/1/48  30.7
2  3/1/48  30.7
3  4/1/48  31.6
4  5/1/48  31.5

#### Multiple jobholder rate

##### Multiple jobholder rate - *Men (1994-2026)*

In [47]:
mjr_men = pd.read_csv('data/Force 2 - Time Scarcity/multiple jobholder rate/multiple_jobholders_men.csv')
mjr_men.head()

     Date  Rate (in thousands)
0  1/1/94                 3627
1  2/1/94                 3692
2  3/1/94                 3889
3  4/1/94                 3841
4  5/1/94                 3973

##### Multiple jobholder rate - *Women (1994-2026)*

In [48]:
mjr_women = pd.read_csv('data/Force 2 - Time Scarcity/multiple jobholder rate/multiple_jobholders_women.csv')
mjr_women.head()

     Date  Rate (in thousands)
0  1/1/94                 3129
1  2/1/94                 3334
2  3/1/94                 3287
3  4/1/94                 3459
4  5/1/94                 3343

##### Multiple Jobholder Rate - *Overall (1994-2026)*

In [49]:
mjr_overall = pd.read_csv('data/Force 2 - Time Scarcity/multiple jobholder rate/multiple_jobholders_overall.csv')
mjr_overall.head()

     Date  Rate (in thousands)
0  1/1/94                 7116
1  2/1/94                 6956
2  3/1/94                 7174
3  4/1/94                 7367
4  5/1/94                 7151

#### Access to paid family leave by state - *as of 202(6?)*

In [50]:
paid_leave = pd.read_csv('data/Force 2 - Time Scarcity/paid family leave/paid_family_leave_available_states.csv')
paid_leave.head()

,State,Enactment Year,Effective Year,Participation,Insurance Type,Parental Leave (Weeks),Family Caregiving (Weeks),Personal Medical (Weeks),Safety Leave (Weeks),Total Annual Paid Leave (Weeks)
0,Alabama,2023,2023,Voluntary,Private Insurance,Set by insurer,Set by insurer,0,0.0,Set by insurer
1,Arkansas,2023,2023,Voluntary,Private Insurance,Set by insurer,Set by insurer,0,0.0,Set by insurer
2,California,2002,2004,Mandatory,Social Insurance,8,8,52,0.0,52
3,Colorado,2020,2023,Mandatory,Social Insurance,12,12,12,12.0,12
4,Connecticut,2019,2021,Mandatory,Social Insurance,12,12,12,1.7,12

### Force 3: Family Formation Friction

#### Percentage of married households *(1940-2024)*

In [51]:
married_households = pd.read_csv('data/Force 3 - Family Formation Friction/married_households.csv')
married_households.head()

   Year  Married households as a percentage of total households
0  2024                                               47.1
1  2023                                               47.3
2  2022                                               46.8
3  2021                                               47.4
4  2020                                               48.5

#### Mean age at first marriage *(1950-2024)*

In [52]:
mean_age_marriage = pd.read_csv('data/Force 3 - Family Formation Friction/mean_age_at_marriage.csv')
mean_age_marriage.head()

   Year   Men  Women
0  2024  30.2   28.6
1  2023  30.2   28.4
2  2022  30.1   28.2
3  2021  30.3   28.6
4  2020  30.5   28.1

#### Divorce Rates

In [53]:
divorce_rate = pd.read_csv('data/Force 3 - Family Formation Friction/divorce_rate_1990_2023.csv')
divorce_rate.head()

,State,2023,2022,2021,2020,2019,2018,2017,2016,2015,...,2007,2006,2005,2004,2003,2002,2001,2000,1995,1990
0,Alabama,3.0,3.2,3.6,3.7,3.6,3.7,3.7,3.8,3.9,...,4.5,4.9,4.9,4.9,5.2,5.4,5.4,5.5,6.0,6.1
1,Alaska,3.1,3.0,3.1,3.2,3.6,3.7,3.6,3.9,4.1,...,4.3,4.2,4.3,4.3,3.9,4.6,4.3,3.9,5.0,5.5
2,Arizona,2.0,2.3,2.7,2.9,2.9,3.0,3.5,3.4,3.6,...,4.0,4.0,4.2,4.3,4.4,4.8,4.0,4.6,6.2,6.9
3,Arkansas,3.0,3.5,3.6,3.6,4.0,4.1,3.7,3.9,4.8,...,5.9,5.8,6.0,6.1,6.0,6.2,6.2,6.4,6.3,6.9
4,California,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.3

#### Marriage Rates

In [54]:
marriage_rate = pd.read_csv('data/Force 3 - Family Formation Friction/marriage_rate_1990_2023.csv')
marriage_rate.head()

,State,2023,2022,2021,2020,2019,2018,2017,2016,2015,...,2007,2006,2005,2004,2003,2002,2001,2000,1995,1990
0,Alabama,6.9,7.3,7.6,7.2,6.7,6.8,7.0,7.1,7.4,...,8.9,9.2,9.2,9.4,9.6,9.9,9.4,10.1,9.8,10.6
1,Alaska,6.4,6.5,6.3,5.7,6.5,6.7,6.9,7.1,7.4,...,8.5,8.2,8.2,8.5,8.1,8.3,8.1,8.9,9.0,10.2
2,Arizona,5.6,5.8,5.4,4.9,5.3,5.5,5.8,5.9,5.9,...,6.4,6.5,6.6,6.7,6.5,6.7,7.6,7.5,8.8,10.0
3,Arkansas,7.8,7.9,8.2,7.8,8.4,8.9,9.5,9.9,10.0,...,12.0,12.4,12.9,13.4,13.4,14.3,14.3,15.4,14.4,15.3
4,California 1,5.5,5.7,5.2,3.2,5.7,6.0,6.3,6.5,6.2,...,6.2,6.3,6.4,6.4,6.1,6.2,6.5,5.8,6.3,7.9

### Force 4: Future Outlook

#### Consumer sentiment index

In [55]:
csi_overall = pd.read_csv('data/Force 4 - Future Outlook/consumer_sentiment_index_2000_2026.csv')
csi_overall.head()

   Month  Year  Index
0      1  2000  112.0
1      2  2000  111.3
2      3  2000  107.1
3      4  2000  109.2
4      5  2000  110.7

##### Consumer sentiment index by region

In [56]:
csi_regions = pd.read_csv('data/Force 4 - Future Outlook/consumer_sentiment_index_within_regions.csv')
csi_regions.head()

   Month  Year  North East  North Central  South   West
0      1  2000       114.9          111.7  111.0  111.4
1      2  2000       113.4          108.0  112.5  111.3
2      3  2000       110.0          104.6  107.0  107.3
3      4  2000       115.4          107.9  106.7  109.4
4      5  2000       110.0          113.5  110.4  108.2

##### Consumer sentiment index by age group

In [57]:
csi_age = pd.read_csv('data/Force 4 - Future Outlook/consumer_sentiment_index_age_groups.csv')
csi_age.head()

   Month  Year  18-34  35-54    55+
0      1  2000  120.0  113.3  103.7
1      2  2000  116.9  112.6  105.3
2      3  2000  110.2  112.5   97.3
3      4  2000  118.3  112.0   98.0
4      5  2000  119.2  112.2  102.2

##### Consumer sentiment index by income terciles

In [58]:
csi_income = pd.read_csv('data/Force 4 - Future Outlook/consumer_sentiment_index_income_terciles.csv')
csi_income.head()

   Month  Year  Lower Third  Middle Third  Upper Third
0      1  2000        100.3         110.5        126.1
1      2  2000        104.4         110.8        121.1
2      3  2000         94.0         108.6        120.0
3      4  2000         96.6         112.9        118.3
4      5  2000         99.7         114.9        117.3

##### Buying conditions for houses

In [59]:
buying_conditions = pd.read_csv('data/Force 4 - Future Outlook/buying_conditions_for_houses.csv')
buying_conditions.head()

,Month,Year,Good time to Buy,Uncertain / Depends,Bad time to Buy,Relative
0,1,2000,73,6,21,152
1,2,2000,74,5,21,153
2,3,2000,72,6,22,150
3,4,2000,72,7,21,151
4,5,2000,65,6,29,136

## Chapter 3: Expectations & Discourse Analysis

### Methodology

### r/Natalism

#### Community Overview

#### Key Themes & Findings

#### Framing & Discourse Patterns

#### Limitations

### r/Childfree

#### Community Overview

#### Key Themes & Findings

#### Framing & Discourse Patterns

#### Limitations

### r/Parenting

#### Community Overview

#### Key Themes & Findings

#### Framing & Discourse Patterns

#### Limitations

### r/Economics

#### Community Overview

#### Key Themes & Findings

#### Framing & Discourse Patterns

#### Limitations